### Profile for Testing Builds

version-current { include "version/current" }
version-edge    { include "version/edge" }
arch-x86_64     { include "arch/x86_64" }
arch-aarch64    { include "arch/aarch64" }

# specific to this profile's builds
test {
  ami_name_prefix = "test"
  ami_desc_prefix = "test"
  build_region    = "us-west-2"
  build_subnet    = "subnet-033a30d7b5220d177"
  ami_regions {
    us-west-2 = true
  }
}

# Build definitions
builds {
  # merge version, arch, profile, and build vars
  current-x86_64 = ${version-current} ${arch-x86_64} ${test} {
    revision = "test"
  }

  # merge version, arch, and profile vars (no build-specific vars)
  edge-x86_64 = ${version-edge} ${arch-x86_64} ${test}

  ### NOTE: aarch64 builds, but won't be launchable, see...
  ### https://github.com/hashicorp/packer/issues/7358
  edge-aarch64 = ${version-edge} ${arch-aarch64} ${test} {
    build_subnet = "subnet-08dfc622745f7d96a"   # other subnet doesn't do a1.* instances
  }
}
